networks:
  apu-network:
    external: true

include:
  - ./geoserver/docker-compose.yml

services:
  api:
    container_name: api
    build:
      context: ./backend/api
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/api/.env.production
    ports:
      - "5001:5000"
    networks:
      - apu-network
    depends_on:
      apu-db:
        condition: service_healthy

  pptx-generator:
    container_name: py
    build:
      context: ./backend/pptx-generator
      dockerfile: Dockerfile.prod
    ports:
      - "8001:8000"
    volumes:
      - ./backend/pptx-generator/app:/app/app
    environment:
      - WORKERS=${WORKERS:-2}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers ${WORKERS:-2}
    networks:
      - apu-network
