networks:
  apu-network:
    external: true

services:
  api:
    container_name: api
    build:
      context: ./backend/api
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/api/.env.production
    ports:
      - "5001:5000"
    networks:
      - apu-network

  pptx-generator:
    container_name: dipp-py
    build:
      context: ./backend/pptx-generator
      dockerfile: Dockerfile.prod
    ports:
      - "8001:8000"
    volumes:
      - ./backend/pptx-generator/app:/app/app
    environment:
      - WORKERS=${WORKERS:-2}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers ${WORKERS:-2}
    networks:
      - apu-network
