volumes:
  apu-gs-data:
  apu-db-data:

networks:
  apu-network:
    external: true
  dipp_network:
    external: true

services:
  apu-db:
    image: kartoza/postgis:${POSTGIS_VERSION_TAG}
    container_name: apu-db
    volumes:
      - apu-db-data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      # - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      # - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m
    networks:
      - apu-network
      - dipp_network

  # apu-geoserver:
  #   image: kartoza/geoserver:${GS_VERSION}
  #   container_name: apu-geoserver
  #   volumes:
  #     - ./fonts:/opt/fonts
  #     - apu-gs-data:/opt/geoserver/data_dir
  #   ports:
  #       # - 8443:8443
  #       - 8601:8080
  #   restart: on-failure
  #   environment:
  #     - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
  #     - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
  #     - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
  #     - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
  #     - INITIAL_MEMORY=${INITIAL_MEMORY}
  #     - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
  #     # - HTTP_PROXY_NAME=korduch.ru
  #     # - GEOSERVER_CONTEXT_ROOT=apu
  #     # - HTTP_SCHEME=https
  #     - PROXY_BASE_URL=https://korduch.ru/apu/geoserver
  #   depends_on:
  #     apu-db:
  #       condition: service_healthy
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u $${GEOSERVER_ADMIN_USER}:$${GEOSERVER_ADMIN_PASSWORD} http://localhost:8080/geoserver/rest/about/version.xml",
  #       ]
  #     interval: 1m30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 1m
  #   networks:
  #     - apu-network
